// <auto-generated />
using System;
using Base.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Base.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210326064140_Item")]
    partial class Item
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Base.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Quantity");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedOn = new DateTime(2021, 3, 25, 23, 41, 40, 629, DateTimeKind.Local).AddTicks(9351),
                            Name = "A",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedOn = new DateTime(2021, 3, 25, 23, 41, 40, 631, DateTimeKind.Local).AddTicks(6457),
                            Name = "B",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedOn = new DateTime(2021, 3, 25, 23, 41, 40, 631, DateTimeKind.Local).AddTicks(6484),
                            Name = "C",
                            Quantity = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
